#ifndef _X86BOX_MNEMONIC_H_
#define _X86BOX_MNEMONIC_H_
#pragma once

namespace x86box {

#define MNEMONIC_MAP_DEF \
	MNEMONIC_DEF(I_INVALID, "???"), \
	MNEMONIC_DEF(I_AAA, "aaa"), \
	MNEMONIC_DEF(I_AAD, "aad"), \
	MNEMONIC_DEF(I_AAM, "aam"), \
	MNEMONIC_DEF(I_AAS, "aas"), \
	MNEMONIC_DEF(I_ADC, "adc"), \
	MNEMONIC_DEF(I_ADD, "add"), \
	MNEMONIC_DEF(I_ADDPD, "addpd"), \
	MNEMONIC_DEF(I_ADDPS, "addps"), \
	MNEMONIC_DEF(I_ADDSD, "addsd"), \
	MNEMONIC_DEF(I_ADDSS, "addss"), \
	MNEMONIC_DEF(I_ADDSUBPD, "addsubpd"), \
	MNEMONIC_DEF(I_ADDSUBPS, "addsubps"), \
	MNEMONIC_DEF(I_AESDEC, "aesdec"), \
	MNEMONIC_DEF(I_AESDECLAST, "aesdeclast"), \
	MNEMONIC_DEF(I_AESENC, "aesenc"), \
	MNEMONIC_DEF(I_AESENCLAST, "aesenclast"), \
	MNEMONIC_DEF(I_AESIMC, "aesimc"), \
	MNEMONIC_DEF(I_AESKEYGENASSIST, "aeskeygenassist"), \
	MNEMONIC_DEF(I_AND, "and"), \
	MNEMONIC_DEF(I_ANDNPD, "andnpd"), \
	MNEMONIC_DEF(I_ANDNPS, "andnps"), \
	MNEMONIC_DEF(I_ANDPD, "andpd"), \
	MNEMONIC_DEF(I_ANDPS, "andps"), \
	MNEMONIC_DEF(I_ARPL, "arpl"), \
	MNEMONIC_DEF(I_BLENDPD, "blendpd"), \
	MNEMONIC_DEF(I_BLENDPS, "blendps"), \
	MNEMONIC_DEF(I_BLENDVPD, "blendvpd"), \
	MNEMONIC_DEF(I_BLENDVPS, "blendvps"), \
	MNEMONIC_DEF(I_BOUND, "bound"), \
	MNEMONIC_DEF(I_BSF, "bsf"), \
	MNEMONIC_DEF(I_BSR, "bsr"), \
	MNEMONIC_DEF(I_LZCNT, "lzcnt"), \
	MNEMONIC_DEF(I_BSWAP, "bswap"), \
	MNEMONIC_DEF(I_BT, "bt"), \
	MNEMONIC_DEF(I_BTC, "btc"), \
	MNEMONIC_DEF(I_BTR, "btr"), \
	MNEMONIC_DEF(I_BTS, "bts"), \
	MNEMONIC_DEF(I_CALL, "call"), \
	MNEMONIC_DEF(I_CALL_FAR, "call"), \
	MNEMONIC_DEF(I_CBW, "cbw"), \
	MNEMONIC_DEF(I_CDQ, "cdq"), \
	MNEMONIC_DEF(I_CDQE, "cdqe"), \
	MNEMONIC_DEF(I_CLC, "clc"), \
	MNEMONIC_DEF(I_CLD, "cld"), \
	MNEMONIC_DEF(I_CLFLUSH, "clflush"), \
	MNEMONIC_DEF(I_CLGI, "clgi"), \
	MNEMONIC_DEF(I_CLI, "cli"), \
	MNEMONIC_DEF(I_CLTS, "clts"), \
	MNEMONIC_DEF(I_CMC, "cmc"), \
	MNEMONIC_DEF(I_CMOVA, "cmova"), \
	MNEMONIC_DEF(I_CMOVAE, "cmovae"), \
	MNEMONIC_DEF(I_CMOVB, "cmovb"), \
	MNEMONIC_DEF(I_CMOVBE, "cmovbe"), \
	MNEMONIC_DEF(I_CMOVE, "cmove"), \
	MNEMONIC_DEF(I_CMOVG, "cmovg"), \
	MNEMONIC_DEF(I_CMOVGE, "cmovge"), \
	MNEMONIC_DEF(I_CMOVL, "cmovl"), \
	MNEMONIC_DEF(I_CMOVLE, "cmovle"), \
	MNEMONIC_DEF(I_CMOVNE, "cmovne"), \
	MNEMONIC_DEF(I_CMOVNO, "cmovno"), \
	MNEMONIC_DEF(I_CMOVNP, "cmovnp"), \
	MNEMONIC_DEF(I_CMOVNS, "cmovns"), \
	MNEMONIC_DEF(I_CMOVO, "cmovo"), \
	MNEMONIC_DEF(I_CMOVP, "cmovp"), \
	MNEMONIC_DEF(I_CMOVS, "cmovs"), \
	MNEMONIC_DEF(I_CMP, "cmp"), \
	MNEMONIC_DEF(I_CMPPD, "cmppd"), \
	MNEMONIC_DEF(I_CMPPS, "cmpps"), \
	MNEMONIC_DEF(I_CMPS, "cmps"), \
	MNEMONIC_DEF(I_CMPSB, "cmpsb"), \
	MNEMONIC_DEF(I_CMPSD, "cmpsd"), \
	MNEMONIC_DEF(I_CMPSQ, "cmpsq"), \
	MNEMONIC_DEF(I_CMPSS, "cmpss"), \
	MNEMONIC_DEF(I_CMPSW, "cmpsw"), \
	MNEMONIC_DEF(I_CMPXCHG, "cmpxchg"), \
	MNEMONIC_DEF(I_CMPXCHG16B, "cmpxchg16b"), \
	MNEMONIC_DEF(I_CMPXCHG8B, "cmpxchg8b"), \
	MNEMONIC_DEF(I_COMISD, "comisd"), \
	MNEMONIC_DEF(I_COMISS, "comiss"), \
	MNEMONIC_DEF(I_CPUID, "cpuid"), \
	MNEMONIC_DEF(I_CQO, "cqo"), \
	MNEMONIC_DEF(I_CRC32, "crc32"), \
	MNEMONIC_DEF(I_CVTDQ2PD, "cvtdq2pd"), \
	MNEMONIC_DEF(I_CVTDQ2PS, "cvtdq2ps"), \
	MNEMONIC_DEF(I_CVTPD2DQ, "cvtpd2dq"), \
	MNEMONIC_DEF(I_CVTPD2PI, "cvtpd2pi"), \
	MNEMONIC_DEF(I_CVTPD2PS, "cvtpd2ps"), \
	MNEMONIC_DEF(I_CVTPI2PD, "cvtpi2pd"), \
	MNEMONIC_DEF(I_CVTPI2PS, "cvtpi2ps"), \
	MNEMONIC_DEF(I_CVTPS2DQ, "cvtps2dq"), \
	MNEMONIC_DEF(I_CVTPS2PD, "cvtps2pd"), \
	MNEMONIC_DEF(I_CVTPS2PI, "cvtps2pi"), \
	MNEMONIC_DEF(I_CVTSD2SI, "cvtsd2si"), \
	MNEMONIC_DEF(I_CVTSD2SS, "cvtsd2ss"), \
	MNEMONIC_DEF(I_CVTSI2SD, "cvtsi2sd"), \
	MNEMONIC_DEF(I_CVTSI2SS, "cvtsi2ss"), \
	MNEMONIC_DEF(I_CVTSS2SD, "cvtss2sd"), \
	MNEMONIC_DEF(I_CVTSS2SI, "cvtss2si"), \
	MNEMONIC_DEF(I_CVTTPD2DQ, "cvttpd2dq"), \
	MNEMONIC_DEF(I_CVTTPD2PI, "cvttpd2pi"), \
	MNEMONIC_DEF(I_CVTTPS2DQ, "cvttps2dq"), \
	MNEMONIC_DEF(I_CVTTPS2PI, "cvttps2pi"), \
	MNEMONIC_DEF(I_CVTTSD2SI, "cvttsd2si"), \
	MNEMONIC_DEF(I_CVTTSS2SI, "cvttss2si"), \
	MNEMONIC_DEF(I_CWD, "cwd"), \
	MNEMONIC_DEF(I_CWDE, "cwde"), \
	MNEMONIC_DEF(I_DAA, "daa"), \
	MNEMONIC_DEF(I_DAS, "das"), \
	MNEMONIC_DEF(I_DEC, "dec"), \
	MNEMONIC_DEF(I_DIV, "div"), \
	MNEMONIC_DEF(I_DIVPD, "divpd"), \
	MNEMONIC_DEF(I_DIVPS, "divps"), \
	MNEMONIC_DEF(I_DIVSD, "divsd"), \
	MNEMONIC_DEF(I_DIVSS, "divss"), \
	MNEMONIC_DEF(I_DPPD, "dppd"), \
	MNEMONIC_DEF(I_DPPS, "dpps"), \
	MNEMONIC_DEF(I_EMMS, "emms"), \
	MNEMONIC_DEF(I_ENTER, "enter"), \
	MNEMONIC_DEF(I_EXTRACTPS, "extractps"), \
	MNEMONIC_DEF(I_F2XM1, "f2xm1"), \
	MNEMONIC_DEF(I_FABS, "fabs"), \
	MNEMONIC_DEF(I_FADD, "fadd"), \
	MNEMONIC_DEF(I_FADDP, "faddp"), \
	MNEMONIC_DEF(I_FBLD, "fbld"), \
	MNEMONIC_DEF(I_FBSTP, "fbstp"), \
	MNEMONIC_DEF(I_FCHS, "fchs"), \
	MNEMONIC_DEF(I_FCMOVB, "fcmovb"), \
	MNEMONIC_DEF(I_FCMOVBE, "fcmovbe"), \
	MNEMONIC_DEF(I_FCMOVE, "fcmove"), \
	MNEMONIC_DEF(I_FCMOVNB, "fcmovnb"), \
	MNEMONIC_DEF(I_FCMOVNBE, "fcmovnbe"), \
	MNEMONIC_DEF(I_FCMOVNE, "fcmovne"), \
	MNEMONIC_DEF(I_FCMOVNU, "fcmovnu"), \
	MNEMONIC_DEF(I_FCMOVU, "fcmovu"), \
	MNEMONIC_DEF(I_FCLEX, "fclex"), \
	MNEMONIC_DEF(I_FCOM, "fcom"), \
	MNEMONIC_DEF(I_FCOM2, "fcom2"), \
	MNEMONIC_DEF(I_FCOMI, "fcomi"), \
	MNEMONIC_DEF(I_FCOMIP, "fcomip"), \
	MNEMONIC_DEF(I_FCOMP, "fcomp"), \
	MNEMONIC_DEF(I_FCOMP3, "fcomp3"), \
	MNEMONIC_DEF(I_FCOMP5, "fcomp5"), \
	MNEMONIC_DEF(I_FCOMPP, "fcompp"), \
	MNEMONIC_DEF(I_FCOS, "fcos"), \
	MNEMONIC_DEF(I_FDECSTP, "fdecstp"), \
	MNEMONIC_DEF(I_FDIV, "fdiv"), \
	MNEMONIC_DEF(I_FDIVP, "fdivp"), \
	MNEMONIC_DEF(I_FDIVR, "fdivr"), \
	MNEMONIC_DEF(I_FDIVRP, "fdivrp"), \
	MNEMONIC_DEF(I_FEMMS, "femms"), \
	MNEMONIC_DEF(I_FFREE, "ffree"), \
	MNEMONIC_DEF(I_FFREEP, "ffreep"), \
	MNEMONIC_DEF(I_FIADD, "fiadd"), \
	MNEMONIC_DEF(I_FICOM, "ficom"), \
	MNEMONIC_DEF(I_FICOMP, "ficomp"), \
	MNEMONIC_DEF(I_FIDIV, "fidiv"), \
	MNEMONIC_DEF(I_FIDIVR, "fidivr"), \
	MNEMONIC_DEF(I_FILD, "fild"), \
	MNEMONIC_DEF(I_FIMUL, "fimul"), \
	MNEMONIC_DEF(I_FINCSTP, "fincstp"), \
	MNEMONIC_DEF(I_FINIT, "finit"), \
	MNEMONIC_DEF(I_FIST, "fist"), \
	MNEMONIC_DEF(I_FISTP, "fistp"), \
	MNEMONIC_DEF(I_FISTTP, "fisttp"), \
	MNEMONIC_DEF(I_FISUB, "fisub"), \
	MNEMONIC_DEF(I_FISUBR, "fisubr"), \
	MNEMONIC_DEF(I_FLD, "fld"), \
	MNEMONIC_DEF(I_FLD1, "fld1"), \
	MNEMONIC_DEF(I_FLDCW, "fldcw"), \
	MNEMONIC_DEF(I_FLDENV, "fldenv"), \
	MNEMONIC_DEF(I_FLDL2E, "fldl2e"), \
	MNEMONIC_DEF(I_FLDL2T, "fldl2t"), \
	MNEMONIC_DEF(I_FLDLG2, "fldlg2"), \
	MNEMONIC_DEF(I_FLDLN2, "fldln2"), \
	MNEMONIC_DEF(I_FLDPI, "fldpi"), \
	MNEMONIC_DEF(I_FLDZ, "fldz"), \
	MNEMONIC_DEF(I_FMUL, "fmul"), \
	MNEMONIC_DEF(I_FMULP, "fmulp"), \
	MNEMONIC_DEF(I_FNCLEX, "fnclex"), \
	MNEMONIC_DEF(I_FNDISI, "fndisi"), \
	MNEMONIC_DEF(I_FNENI, "fneni"), \
	MNEMONIC_DEF(I_FNINIT, "fninit"), \
	MNEMONIC_DEF(I_FNOP, "fnop"), \
	MNEMONIC_DEF(I_FNSAVE, "fnsave"), \
	MNEMONIC_DEF(I_FSETPM, "fsetpm"), \
	MNEMONIC_DEF(I_FNSTCW, "fnstcw"), \
	MNEMONIC_DEF(I_FNSTENV, "fnstenv"), \
	MNEMONIC_DEF(I_FNSTSW, "fnstsw"), \
	MNEMONIC_DEF(I_FPATAN, "fpatan"), \
	MNEMONIC_DEF(I_FPREM, "fprem"), \
	MNEMONIC_DEF(I_FPREM1, "fprem1"), \
	MNEMONIC_DEF(I_FPTAN, "fptan"), \
	MNEMONIC_DEF(I_FRNDINT, "frndint"), \
	MNEMONIC_DEF(I_FRSTOR, "frstor"), \
	MNEMONIC_DEF(I_FRSTPM, "frstpm"), \
	MNEMONIC_DEF(I_FSAVE, "fsave"), \
	MNEMONIC_DEF(I_FSCALE, "fscale"), \
	MNEMONIC_DEF(I_FSIN, "fsin"), \
	MNEMONIC_DEF(I_FSINCOS, "fsincos"), \
	MNEMONIC_DEF(I_FSQRT, "fsqrt"), \
	MNEMONIC_DEF(I_FST, "fst"), \
	MNEMONIC_DEF(I_FSTCW, "fstcw"), \
	MNEMONIC_DEF(I_FSTENV, "fstenv"), \
	MNEMONIC_DEF(I_FSTP, "fstp"), \
	MNEMONIC_DEF(I_FSTP1, "fstp1"), \
	MNEMONIC_DEF(I_FSTP8, "fstp8"), \
	MNEMONIC_DEF(I_FSTP9, "fstp9"), \
	MNEMONIC_DEF(I_FSTSW, "fstsw"), \
	MNEMONIC_DEF(I_FSUB, "fsub"), \
	MNEMONIC_DEF(I_FSUBP, "fsubp"), \
	MNEMONIC_DEF(I_FSUBR, "fsubr"), \
	MNEMONIC_DEF(I_FSUBRP, "fsubrp"), \
	MNEMONIC_DEF(I_FTST, "ftst"), \
	MNEMONIC_DEF(I_FUCOM, "fucom"), \
	MNEMONIC_DEF(I_FUCOMI, "fucomi"), \
	MNEMONIC_DEF(I_FUCOMIP, "fucomip"), \
	MNEMONIC_DEF(I_FUCOMP, "fucomp"), \
	MNEMONIC_DEF(I_FUCOMPP, "fucompp"), \
	MNEMONIC_DEF(I_FXAM, "fxam"), \
	MNEMONIC_DEF(I_FXCH, "fxch"), \
	MNEMONIC_DEF(I_FXCH4, "fxch4"), \
	MNEMONIC_DEF(I_FXCH7, "fxch7"), \
	MNEMONIC_DEF(I_FXRSTOR, "fxrstor"), \
	MNEMONIC_DEF(I_FXSAVE, "fxsave"), \
	MNEMONIC_DEF(I_FXTRACT, "fxtract"), \
	MNEMONIC_DEF(I_FYL2X, "fyl2x"), \
	MNEMONIC_DEF(I_FYL2XP1, "fyl2xp1"), \
	MNEMONIC_DEF(I_HADDPD, "haddpd"), \
	MNEMONIC_DEF(I_HADDPS, "haddps"), \
	MNEMONIC_DEF(I_HINT_NOP, "hint_nop"), \
	MNEMONIC_DEF(I_HLT, "hlt"), \
	MNEMONIC_DEF(I_HSUBPD, "hsubpd"), \
	MNEMONIC_DEF(I_HSUBPS, "hsubps"), \
	MNEMONIC_DEF(I_IDIV, "idiv"), \
	MNEMONIC_DEF(I_IMUL, "imul"), \
	MNEMONIC_DEF(I_IN, "in"), \
	MNEMONIC_DEF(I_INC, "inc"), \
	MNEMONIC_DEF(I_INSB, "insb"), \
	MNEMONIC_DEF(I_INSD, "insd"), \
	MNEMONIC_DEF(I_INSERTPS, "insertps"), \
	MNEMONIC_DEF(I_INSW, "insw"), \
	MNEMONIC_DEF(I_INT, "int"), \
	MNEMONIC_DEF(I_INT1, "int1"), \
	MNEMONIC_DEF(I_INT3, "int3"), \
	MNEMONIC_DEF(I_INTO, "into"), \
	MNEMONIC_DEF(I_INVD, "invd"), \
	MNEMONIC_DEF(I_INVLPG, "invlpg"), \
	MNEMONIC_DEF(I_INVLPGA, "invlpga"), \
	MNEMONIC_DEF(I_IRETD, "iretd"), \
	MNEMONIC_DEF(I_IRETQ, "iretq"), \
	MNEMONIC_DEF(I_IRETW, "iretw"), \
	MNEMONIC_DEF(I_JA, "ja"), \
	MNEMONIC_DEF(I_JAE, "jae"), \
	MNEMONIC_DEF(I_JB, "jb"), \
	MNEMONIC_DEF(I_JBE, "jbe"), \
	MNEMONIC_DEF(I_JCXZ, "jcxz"), \
	MNEMONIC_DEF(I_JE, "je"), \
	MNEMONIC_DEF(I_JECXZ, "jecxz"), \
	MNEMONIC_DEF(I_JG, "jg"), \
	MNEMONIC_DEF(I_JGE, "jge"), \
	MNEMONIC_DEF(I_JL, "jl"), \
	MNEMONIC_DEF(I_JLE, "jle"), \
	MNEMONIC_DEF(I_JMP, "jmp"), \
	MNEMONIC_DEF(I_JMP_FAR, "jmp"), \
	MNEMONIC_DEF(I_JNE, "jne"), \
	MNEMONIC_DEF(I_JNO, "jno"), \
	MNEMONIC_DEF(I_JNP, "jnp"), \
	MNEMONIC_DEF(I_JNS, "jns"), \
	MNEMONIC_DEF(I_JO, "jo"), \
	MNEMONIC_DEF(I_JP, "jp"), \
	MNEMONIC_DEF(I_JRCXZ, "jrcxz"), \
	MNEMONIC_DEF(I_JS, "js"), \
	MNEMONIC_DEF(I_LAHF, "lahf"), \
	MNEMONIC_DEF(I_LAR, "lar"), \
	MNEMONIC_DEF(I_LDDQU, "lddqu"), \
	MNEMONIC_DEF(I_LDMXCSR, "ldmxcsr"), \
	MNEMONIC_DEF(I_LDS, "lds"), \
	MNEMONIC_DEF(I_LEA, "lea"), \
	MNEMONIC_DEF(I_LEAVE, "leave"), \
	MNEMONIC_DEF(I_LES, "les"), \
	MNEMONIC_DEF(I_LFENCE, "lfence"), \
	MNEMONIC_DEF(I_LFS, "lfs"), \
	MNEMONIC_DEF(I_LGDT, "lgdt"), \
	MNEMONIC_DEF(I_LGS, "lgs"), \
	MNEMONIC_DEF(I_LIDT, "lidt"), \
	MNEMONIC_DEF(I_LLDT, "lldt"), \
	MNEMONIC_DEF(I_LMSW, "lmsw"), \
	MNEMONIC_DEF(I_LODS, "lods"), \
	MNEMONIC_DEF(I_LODSB, "lodsb"), \
	MNEMONIC_DEF(I_LODSD, "lodsd"), \
	MNEMONIC_DEF(I_LODSQ, "lodsq"), \
	MNEMONIC_DEF(I_LODSW, "lodsw"), \
	MNEMONIC_DEF(I_LOOP, "loop"), \
	MNEMONIC_DEF(I_LOOPE, "loope"), \
	MNEMONIC_DEF(I_LOOPNE, "loopne"), \
	MNEMONIC_DEF(I_LSL, "lsl"), \
	MNEMONIC_DEF(I_LSS, "lss"), \
	MNEMONIC_DEF(I_LTR, "ltr"), \
	MNEMONIC_DEF(I_MASKMOVDQU, "maskmovdqu"), \
	MNEMONIC_DEF(I_MASKMOVQ, "maskmovq"), \
	MNEMONIC_DEF(I_MAXPD, "maxpd"), \
	MNEMONIC_DEF(I_MAXPS, "maxps"), \
	MNEMONIC_DEF(I_MAXSD, "maxsd"), \
	MNEMONIC_DEF(I_MAXSS, "maxss"), \
	MNEMONIC_DEF(I_MFENCE, "mfence"), \
	MNEMONIC_DEF(I_MINPD, "minpd"), \
	MNEMONIC_DEF(I_MINPS, "minps"), \
	MNEMONIC_DEF(I_MINSD, "minsd"), \
	MNEMONIC_DEF(I_MINSS, "minss"), \
	MNEMONIC_DEF(I_MONITOR, "monitor"), \
	MNEMONIC_DEF(I_MOV, "mov"), \
	MNEMONIC_DEF(I_MOVAPD, "movapd"), \
	MNEMONIC_DEF(I_MOVAPS, "movaps"), \
	MNEMONIC_DEF(I_MOVD, "movd"), \
	MNEMONIC_DEF(I_MOVDDUP, "movddup"), \
	MNEMONIC_DEF(I_MOVDQ2Q, "movdq2q"), \
	MNEMONIC_DEF(I_MOVDQA, "movdqa"), \
	MNEMONIC_DEF(I_MOVDQU, "movdqu"), \
	MNEMONIC_DEF(I_MOVHLPS, "movhlps"), \
	MNEMONIC_DEF(I_MOVHPD, "movhpd"), \
	MNEMONIC_DEF(I_MOVHPS, "movhps"), \
	MNEMONIC_DEF(I_MOVLHPS, "movlhps"), \
	MNEMONIC_DEF(I_MOVLPD, "movlpd"), \
	MNEMONIC_DEF(I_MOVLPS, "movlps"), \
	MNEMONIC_DEF(I_MOVMSKPD, "movmskpd"), \
	MNEMONIC_DEF(I_MOVMSKPS, "movmskps"), \
	MNEMONIC_DEF(I_MOVNTDQ, "movntdq"), \
	MNEMONIC_DEF(I_MOVNTDQA, "movntdqa"), \
	MNEMONIC_DEF(I_MOVNTI, "movnti"), \
	MNEMONIC_DEF(I_MOVNTPD, "movntpd"), \
	MNEMONIC_DEF(I_MOVNTPS, "movntps"), \
	MNEMONIC_DEF(I_MOVNTQ, "movntq"), \
	MNEMONIC_DEF(I_MOVQ, "movq"), \
	MNEMONIC_DEF(I_MOVQ2DQ, "movq2dq"), \
	MNEMONIC_DEF(I_MOVS, "movs"), \
	MNEMONIC_DEF(I_MOVSB, "movsb"), \
	MNEMONIC_DEF(I_MOVSD, "movsd"), \
	MNEMONIC_DEF(I_MOVSHDUP, "movshdup"), \
	MNEMONIC_DEF(I_MOVSLDUP, "movsldup"), \
	MNEMONIC_DEF(I_MOVSQ, "movsq"), \
	MNEMONIC_DEF(I_MOVSS, "movss"), \
	MNEMONIC_DEF(I_MOVSW, "movsw"), \
	MNEMONIC_DEF(I_MOVSX, "movsx"), \
	MNEMONIC_DEF(I_MOVSXD, "movsxd"), \
	MNEMONIC_DEF(I_MOVUPD, "movupd"), \
	MNEMONIC_DEF(I_MOVUPS, "movups"), \
	MNEMONIC_DEF(I_MOVZX, "movzx"), \
	MNEMONIC_DEF(I_MPSADBW, "mpsadbw"), \
	MNEMONIC_DEF(I_MUL, "mul"), \
	MNEMONIC_DEF(I_MULPD, "mulpd"), \
	MNEMONIC_DEF(I_MULPS, "mulps"), \
	MNEMONIC_DEF(I_MULSD, "mulsd"), \
	MNEMONIC_DEF(I_MULSS, "mulss"), \
	MNEMONIC_DEF(I_MWAIT, "mwait"), \
	MNEMONIC_DEF(I_NEG, "neg"), \
	MNEMONIC_DEF(I_NOP, "nop"), \
	MNEMONIC_DEF(I_PREFETCH, "prefetch"), \
	MNEMONIC_DEF(I_PREFETCHW, "prefetchw"), \
	MNEMONIC_DEF(I_NOT, "not"), \
	MNEMONIC_DEF(I_OR, "or"), \
	MNEMONIC_DEF(I_ORPD, "orpd"), \
	MNEMONIC_DEF(I_ORPS, "orps"), \
	MNEMONIC_DEF(I_OUT, "out"), \
	MNEMONIC_DEF(I_OUTS, "outs"), \
	MNEMONIC_DEF(I_OUTSB, "outsb"), \
	MNEMONIC_DEF(I_OUTSD, "outsd"), \
	MNEMONIC_DEF(I_OUTSW, "outsw"), \
	MNEMONIC_DEF(I_PABSB, "pabsb"), \
	MNEMONIC_DEF(I_PABSD, "pabsd"), \
	MNEMONIC_DEF(I_PABSW, "pabsw"), \
	MNEMONIC_DEF(I_PACKSSDW, "packssdw"), \
	MNEMONIC_DEF(I_PACKSSWB, "packsswb"), \
	MNEMONIC_DEF(I_PACKUSDW, "packusdw"), \
	MNEMONIC_DEF(I_PACKUSWB, "packuswb"), \
	MNEMONIC_DEF(I_PADDB, "paddb"), \
	MNEMONIC_DEF(I_PADDD, "paddd"), \
	MNEMONIC_DEF(I_PADDQ, "paddq"), \
	MNEMONIC_DEF(I_PADDSB, "paddsb"), \
	MNEMONIC_DEF(I_PADDSW, "paddsw"), \
	MNEMONIC_DEF(I_PADDUSB, "paddusb"), \
	MNEMONIC_DEF(I_PADDUSW, "paddusw"), \
	MNEMONIC_DEF(I_PADDW, "paddw"), \
	MNEMONIC_DEF(I_PALIGNR, "palignr"), \
	MNEMONIC_DEF(I_PAND, "pand"), \
	MNEMONIC_DEF(I_PANDN, "pandn"), \
	MNEMONIC_DEF(I_PAUSE, "pause"), \
	MNEMONIC_DEF(I_PAVGB, "pavgb"), \
	MNEMONIC_DEF(I_PAVGW, "pavgw"), \
	MNEMONIC_DEF(I_PBLENDVB, "pblendvb"), \
	MNEMONIC_DEF(I_PBLENDW, "pblendw"), \
	MNEMONIC_DEF(I_PCLMULHQHQDQ, "pclmulhqhqdq"), \
	MNEMONIC_DEF(I_PCLMULHQLQDQ, "pclmulhqlqdq"), \
	MNEMONIC_DEF(I_PCLMULLQHQDQ, "pclmullqhqdq"), \
	MNEMONIC_DEF(I_PCLMULLQLQDQ, "pclmullqlqdq"), \
	MNEMONIC_DEF(I_PCLMULQDQ, "pclmulqdq"), \
	MNEMONIC_DEF(I_PCMPEQB, "pcmpeqb"), \
	MNEMONIC_DEF(I_PCMPEQD, "pcmpeqd"), \
	MNEMONIC_DEF(I_PCMPEQQ, "pcmpeqq"), \
	MNEMONIC_DEF(I_PCMPEQW, "pcmpeqw"), \
	MNEMONIC_DEF(I_PCMPESTRI, "pcmpestri"), \
	MNEMONIC_DEF(I_PCMPISTRM, "pcmpistrm"), \
	MNEMONIC_DEF(I_PCMPESTRM, "pcmpestrm"), \
	MNEMONIC_DEF(I_PCMPGTB, "pcmpgtb"), \
	MNEMONIC_DEF(I_PCMPGTD, "pcmpgtd"), \
	MNEMONIC_DEF(I_PCMPGTQ, "pcmpgtq"), \
	MNEMONIC_DEF(I_PCMPGTW, "pcmpgtw"), \
	MNEMONIC_DEF(I_PCMPISTRI, "pcmpistri"), \
	MNEMONIC_DEF(I_PEXTRB, "pextrb"), \
	MNEMONIC_DEF(I_PEXTRD, "pextrd"), \
	MNEMONIC_DEF(I_PEXTRQ, "pextrq"), \
	MNEMONIC_DEF(I_PEXTRW, "pextrw"), \
	MNEMONIC_DEF(I_EXTRQ, "extrq"), \
	MNEMONIC_DEF(I_PHADDD, "phaddd"), \
	MNEMONIC_DEF(I_PHADDSW, "phaddsw"), \
	MNEMONIC_DEF(I_PHADDW, "phaddw"), \
	MNEMONIC_DEF(I_PHMINPOSUW, "phminposuw"), \
	MNEMONIC_DEF(I_PHSUBD, "phsubd"), \
	MNEMONIC_DEF(I_PHSUBSW, "phsubsw"), \
	MNEMONIC_DEF(I_PHSUBW, "phsubw"), \
	MNEMONIC_DEF(I_PINSRB, "pinsrb"), \
	MNEMONIC_DEF(I_PINSRD, "pinsrd"), \
	MNEMONIC_DEF(I_PINSRQ, "pinsrq"), \
	MNEMONIC_DEF(I_PINSRW, "pinsrw"), \
	MNEMONIC_DEF(I_PMADDUBSW, "pmaddubsw"), \
	MNEMONIC_DEF(I_PMADDWD, "pmaddwd"), \
	MNEMONIC_DEF(I_PMAXSB, "pmaxsb"), \
	MNEMONIC_DEF(I_PMAXSD, "pmaxsd"), \
	MNEMONIC_DEF(I_PMAXSW, "pmaxsw"), \
	MNEMONIC_DEF(I_PMAXUB, "pmaxub"), \
	MNEMONIC_DEF(I_PMAXUD, "pmaxud"), \
	MNEMONIC_DEF(I_PMAXUW, "pmaxuw"), \
	MNEMONIC_DEF(I_PMINSB, "pminsb"), \
	MNEMONIC_DEF(I_PMINSD, "pminsd"), \
	MNEMONIC_DEF(I_PMINSW, "pminsw"), \
	MNEMONIC_DEF(I_PMINUB, "pminub"), \
	MNEMONIC_DEF(I_PMINUD, "pminud"), \
	MNEMONIC_DEF(I_PMINUW, "pminuw"), \
	MNEMONIC_DEF(I_PMOVMSKB, "pmovmskb"), \
	MNEMONIC_DEF(I_PMOVSXBD, "pmovsxbd"), \
	MNEMONIC_DEF(I_PMOVSXBQ, "pmovsxbq"), \
	MNEMONIC_DEF(I_PMOVSXBW, "pmovsxbw"), \
	MNEMONIC_DEF(I_PMOVSXDQ, "pmovsxdq"), \
	MNEMONIC_DEF(I_PMOVSXWD, "pmovsxwd"), \
	MNEMONIC_DEF(I_PMOVSXWQ, "pmovsxwq"), \
	MNEMONIC_DEF(I_PMOVZXBD, "pmovzxbd"), \
	MNEMONIC_DEF(I_PMOVZXBQ, "pmovzxbq"), \
	MNEMONIC_DEF(I_PMOVZXBW, "pmovzxbw"), \
	MNEMONIC_DEF(I_PMOVZXDQ, "pmovzxdq"), \
	MNEMONIC_DEF(I_PMOVZXWD, "pmovzxwd"), \
	MNEMONIC_DEF(I_PMOVZXWQ, "pmovzxwq"), \
	MNEMONIC_DEF(I_PMULDQ, "pmuldq"), \
	MNEMONIC_DEF(I_PMULHRSW, "pmulhrsw"), \
	MNEMONIC_DEF(I_PMULHUW, "pmulhuw"), \
	MNEMONIC_DEF(I_PMULHW, "pmulhw"), \
	MNEMONIC_DEF(I_PMULLD, "pmulld"), \
	MNEMONIC_DEF(I_PMULLW, "pmullw"), \
	MNEMONIC_DEF(I_PMULUDQ, "pmuludq"), \
	MNEMONIC_DEF(I_POP, "pop"), \
	MNEMONIC_DEF(I_POPAW, "popaw"), \
	MNEMONIC_DEF(I_POPAD, "popad"), \
	MNEMONIC_DEF(I_POPCNT, "popcnt"), \
	MNEMONIC_DEF(I_POPFW, "popfw"), \
	MNEMONIC_DEF(I_POPFD, "popfd"), \
	MNEMONIC_DEF(I_POPFQ, "popfq"), \
	MNEMONIC_DEF(I_POR, "por"), \
	MNEMONIC_DEF(I_PREFETCHNTA, "prefetchnta"), \
	MNEMONIC_DEF(I_PREFETCHT0, "prefetcht0"), \
	MNEMONIC_DEF(I_PREFETCHT1, "prefetcht1"), \
	MNEMONIC_DEF(I_PREFETCHT2, "prefetcht2"), \
	MNEMONIC_DEF(I_PSADBW, "psadbw"), \
	MNEMONIC_DEF(I_PSHUFB, "pshufb"), \
	MNEMONIC_DEF(I_PSHUFD, "pshufd"), \
	MNEMONIC_DEF(I_PSHUFHW, "pshufhw"), \
	MNEMONIC_DEF(I_PSHUFLW, "pshuflw"), \
	MNEMONIC_DEF(I_PSHUFW, "pshufw"), \
	MNEMONIC_DEF(I_PSIGNB, "psignb"), \
	MNEMONIC_DEF(I_PSIGND, "psignd"), \
	MNEMONIC_DEF(I_PSIGNW, "psignw"), \
	MNEMONIC_DEF(I_PSLLD, "pslld"), \
	MNEMONIC_DEF(I_PSLLDQ, "pslldq"), \
	MNEMONIC_DEF(I_PSLLQ, "psllq"), \
	MNEMONIC_DEF(I_PSLLW, "psllw"), \
	MNEMONIC_DEF(I_PSRAD, "psrad"), \
	MNEMONIC_DEF(I_PSRAW, "psraw"), \
	MNEMONIC_DEF(I_PSRLD, "psrld"), \
	MNEMONIC_DEF(I_PSRLDQ, "psrldq"), \
	MNEMONIC_DEF(I_PSRLQ, "psrlq"), \
	MNEMONIC_DEF(I_PSRLW, "psrlw"), \
	MNEMONIC_DEF(I_PSUBB, "psubb"), \
	MNEMONIC_DEF(I_PSUBD, "psubd"), \
	MNEMONIC_DEF(I_PSUBQ, "psubq"), \
	MNEMONIC_DEF(I_PSUBSB, "psubsb"), \
	MNEMONIC_DEF(I_PSUBSW, "psubsw"), \
	MNEMONIC_DEF(I_PSUBUSB, "psubusb"), \
	MNEMONIC_DEF(I_PSUBUSW, "psubusw"), \
	MNEMONIC_DEF(I_PSUBW, "psubw"), \
	MNEMONIC_DEF(I_PTEST, "ptest"), \
	MNEMONIC_DEF(I_PUNPCKHBW, "punpckhbw"), \
	MNEMONIC_DEF(I_PUNPCKHDQ, "punpckhdq"), \
	MNEMONIC_DEF(I_PUNPCKHQDQ, "punpckhqdq"), \
	MNEMONIC_DEF(I_PUNPCKHWD, "punpckhwd"), \
	MNEMONIC_DEF(I_PUNPCKLBW, "punpcklbw"), \
	MNEMONIC_DEF(I_PUNPCKLDQ, "punpckldq"), \
	MNEMONIC_DEF(I_PUNPCKLQDQ, "punpcklqdq"), \
	MNEMONIC_DEF(I_PUNPCKLWD, "punpcklwd"), \
	MNEMONIC_DEF(I_PUSH, "push"), \
	MNEMONIC_DEF(I_PUSHAW, "pushaw"), \
	MNEMONIC_DEF(I_PUSHAD, "pushad"), \
	MNEMONIC_DEF(I_PUSHFW, "pushfw"), \
	MNEMONIC_DEF(I_PUSHFD, "pushfd"), \
	MNEMONIC_DEF(I_PUSHFQ, "pushfq"), \
	MNEMONIC_DEF(I_PUSHF, "pushf"), \
	MNEMONIC_DEF(I_PXOR, "pxor"), \
	MNEMONIC_DEF(I_RCL, "rcl"), \
	MNEMONIC_DEF(I_RCPPS, "rcpps"), \
	MNEMONIC_DEF(I_RCPSS, "rcpss"), \
	MNEMONIC_DEF(I_RCR, "rcr"), \
	MNEMONIC_DEF(I_RDMSR, "rdmsr"), \
	MNEMONIC_DEF(I_RDPMC, "rdpmc"), \
	MNEMONIC_DEF(I_RDTSC, "rdtsc"), \
	MNEMONIC_DEF(I_RDTSCP, "rdtscp"), \
	MNEMONIC_DEF(I_RET, "ret"), \
	MNEMONIC_DEF(I_RETF, "retf"), \
	MNEMONIC_DEF(I_RETN, "retn"), \
	MNEMONIC_DEF(I_ROL, "rol"), \
	MNEMONIC_DEF(I_ROR, "ror"), \
	MNEMONIC_DEF(I_ROUNDPD, "roundpd"), \
	MNEMONIC_DEF(I_ROUNDPS, "roundps"), \
	MNEMONIC_DEF(I_ROUNDSD, "roundsd"), \
	MNEMONIC_DEF(I_ROUNDSS, "roundss"), \
	MNEMONIC_DEF(I_RSM, "rsm"), \
	MNEMONIC_DEF(I_RSQRTPS, "rsqrtps"), \
	MNEMONIC_DEF(I_RSQRTSS, "rsqrtss"), \
	MNEMONIC_DEF(I_SAHF, "sahf"), \
	MNEMONIC_DEF(I_SAL, "sal"), \
	MNEMONIC_DEF(I_SALC, "salc"), \
	MNEMONIC_DEF(I_SAR, "sar"), \
	MNEMONIC_DEF(I_SBB, "sbb"), \
	MNEMONIC_DEF(I_SCASB, "scasb"), \
	MNEMONIC_DEF(I_SCASD, "scasd"), \
	MNEMONIC_DEF(I_SCASQ, "scasq"), \
	MNEMONIC_DEF(I_SCASW, "scasw"), \
	MNEMONIC_DEF(I_SETA, "seta"), \
	MNEMONIC_DEF(I_SETAE, "setae"), \
	MNEMONIC_DEF(I_SETB, "setb"), \
	MNEMONIC_DEF(I_SETBE, "setbe"), \
	MNEMONIC_DEF(I_SETE, "sete"), \
	MNEMONIC_DEF(I_SETG, "setg"), \
	MNEMONIC_DEF(I_SETGE, "setge"), \
	MNEMONIC_DEF(I_SETL, "setl"), \
	MNEMONIC_DEF(I_SETLE, "setle"), \
	MNEMONIC_DEF(I_SETNE, "setne"), \
	MNEMONIC_DEF(I_SETNO, "setno"), \
	MNEMONIC_DEF(I_SETNP, "setnp"), \
	MNEMONIC_DEF(I_SETNS, "setns"), \
	MNEMONIC_DEF(I_SETO, "seto"), \
	MNEMONIC_DEF(I_SETP, "setp"), \
	MNEMONIC_DEF(I_SETS, "sets"), \
	MNEMONIC_DEF(I_SFENCE, "sfence"), \
	MNEMONIC_DEF(I_SGDT, "sgdt"), \
	MNEMONIC_DEF(I_SHL, "shl"), \
	MNEMONIC_DEF(I_SHLD, "shld"), \
	MNEMONIC_DEF(I_SHR, "shr"), \
	MNEMONIC_DEF(I_SHRD, "shrd"), \
	MNEMONIC_DEF(I_SHUFPD, "shufpd"), \
	MNEMONIC_DEF(I_SHUFPS, "shufps"), \
	MNEMONIC_DEF(I_SIDT, "sidt"), \
	MNEMONIC_DEF(I_SKINIT, "skinit"), \
	MNEMONIC_DEF(I_SLDT, "sldt"), \
	MNEMONIC_DEF(I_SMSW, "smsw"), \
	MNEMONIC_DEF(I_SQRTPD, "sqrtpd"), \
	MNEMONIC_DEF(I_SQRTPS, "sqrtps"), \
	MNEMONIC_DEF(I_SQRTSD, "sqrtsd"), \
	MNEMONIC_DEF(I_SQRTSS, "sqrtss"), \
	MNEMONIC_DEF(I_STC, "stc"), \
	MNEMONIC_DEF(I_STD, "std"), \
	MNEMONIC_DEF(I_STGI, "stgi"), \
	MNEMONIC_DEF(I_STI, "sti"), \
	MNEMONIC_DEF(I_STMXCSR, "stmxcsr"), \
	MNEMONIC_DEF(I_STOSB, "stosb"), \
	MNEMONIC_DEF(I_STOSD, "stosd"), \
	MNEMONIC_DEF(I_STOSQ, "stosq"), \
	MNEMONIC_DEF(I_STOSW, "stosw"), \
	MNEMONIC_DEF(I_STR, "str"), \
	MNEMONIC_DEF(I_SUB, "sub"), \
	MNEMONIC_DEF(I_SUBPD, "subpd"), \
	MNEMONIC_DEF(I_SUBPS, "subps"), \
	MNEMONIC_DEF(I_SUBSD, "subsd"), \
	MNEMONIC_DEF(I_SUBSS, "subss"), \
	MNEMONIC_DEF(I_SWAPGS, "swapgs"), \
	MNEMONIC_DEF(I_SYSCALL, "syscall"), \
	MNEMONIC_DEF(I_SYSENTER, "sysenter"), \
	MNEMONIC_DEF(I_SYSEXIT, "sysexit"), \
	MNEMONIC_DEF(I_SYSRET, "sysret"), \
	MNEMONIC_DEF(I_TEST, "test"), \
	MNEMONIC_DEF(I_UCOMISD, "ucomisd"), \
	MNEMONIC_DEF(I_UCOMISS, "ucomiss"), \
	MNEMONIC_DEF(I_UD2, "ud2"), \
	MNEMONIC_DEF(I_UNPCKHPD, "unpckhpd"), \
	MNEMONIC_DEF(I_UNPCKHPS, "unpckhps"), \
	MNEMONIC_DEF(I_UNPCKLPD, "unpcklpd"), \
	MNEMONIC_DEF(I_UNPCKLPS, "unpcklps"), \
	MNEMONIC_DEF(I_VERR, "verr"), \
	MNEMONIC_DEF(I_VERW, "verw"), \
	MNEMONIC_DEF(I_VMCALL, "vmcall"), \
	MNEMONIC_DEF(I_VMCLEAR, "vmclear"), \
	MNEMONIC_DEF(I_VMLAUNCH, "vmlaunch"), \
	MNEMONIC_DEF(I_VMLOAD, "vmload"), \
	MNEMONIC_DEF(I_VMMCALL, "vmmcall"), \
	MNEMONIC_DEF(I_VMPTRLD, "vmptrld"), \
	MNEMONIC_DEF(I_VMPTRST, "vmptrst"), \
	MNEMONIC_DEF(I_VMREAD, "vmread"), \
	MNEMONIC_DEF(I_VMRESUME, "vmresume"), \
	MNEMONIC_DEF(I_VMRUN, "vmrun"), \
	MNEMONIC_DEF(I_VMSAVE, "vmsave"), \
	MNEMONIC_DEF(I_VMWRITE, "vmwrite"), \
	MNEMONIC_DEF(I_VMXOFF, "vmxoff"), \
	MNEMONIC_DEF(I_VMXON, "vmxon"), \
	MNEMONIC_DEF(I_WAIT, "wait"), \
	MNEMONIC_DEF(I_WBINVD, "wbinvd"), \
	MNEMONIC_DEF(I_WRMSR, "wrmsr"), \
	MNEMONIC_DEF(I_XADD, "xadd"), \
	MNEMONIC_DEF(I_XCHG, "xchg"), \
	MNEMONIC_DEF(I_XGETBV, "xgetbv"), \
	MNEMONIC_DEF(I_XLATB, "xlatb"), \
	MNEMONIC_DEF(I_XOR, "xor"), \
	MNEMONIC_DEF(I_XORPD, "xorpd"), \
	MNEMONIC_DEF(I_XORPS, "xorps"), \
	MNEMONIC_DEF(I_XRSTOR, "xrstor"), \
	MNEMONIC_DEF(I_XRSTORS, "xrstors"), \
	MNEMONIC_DEF(I_XSAVE, "xsave"), \
	MNEMONIC_DEF(I_XSAVEC, "xsavec"), \
	MNEMONIC_DEF(I_XSAVEOPT, "xsaveopt"), \
	MNEMONIC_DEF(I_XSAVES, "xsaves"), \
	MNEMONIC_DEF(I_XSETBV, "xsetbv"), \
	MNEMONIC_DEF(I_VPSLLDQ, "vpslldq"), \
	MNEMONIC_DEF(I_VFMADDPS, "vfmaddps"), \
	MNEMONIC_DEF(I_VFMADDPD, "vfmaddpd"), \
	MNEMONIC_DEF(I_VFMADDSS, "vfmaddss"), \
	MNEMONIC_DEF(I_VFMADDSD, "vfmaddsd"), \
	MNEMONIC_DEF(I_VFMSUBPS, "VFMSUBPS"), \
	MNEMONIC_DEF(I_VFMSUBPD, "vfmsubpd"), \
	MNEMONIC_DEF(I_VFMSUBSS, "vfmsubss"), \
	MNEMONIC_DEF(I_VFMSUBSD, "vfmsubsd"), \
	MNEMONIC_DEF(I_VFMADDSUBPS, "vfmaddsubps"), \
	MNEMONIC_DEF(I_VFMADDSUBPD, "vfmaddsubpd"), \
	MNEMONIC_DEF(I_VFMSUBADDPS, "vfmsubaddps"), \
	MNEMONIC_DEF(I_VFMSUBADDPD, "vfmsubaddpd"), \
	MNEMONIC_DEF(I_VFNMADDPS, "vfnmaddps"), \
	MNEMONIC_DEF(I_VFNMADDPD, "vfnmaddpd"), \
	MNEMONIC_DEF(I_VFNMADDSS, "vfnmaddss"), \
	MNEMONIC_DEF(I_VFNMADDSD, "vfnmaddsd"), \
	MNEMONIC_DEF(I_VFNMSUBPS, "vfnmsubps"), \
	MNEMONIC_DEF(I_VFNMSUBPD, "vfnmsubpd"), \
	MNEMONIC_DEF(I_VFNMSUBSS, "vfnmsubss"), \
	MNEMONIC_DEF(I_VFNMSUBSD, "vfnmsubsd"), \
	MNEMONIC_DEF(I_VCMPPS, "vcmpps"), \
	MNEMONIC_DEF(I_VCMPSS, "vcmpss"), \
	MNEMONIC_DEF(I_VCMPPD, "vcmppd"), \
	MNEMONIC_DEF(I_VCMPSD, "vcmpsd"), \
	MNEMONIC_DEF(I_VPINSRW, "vpinsrw"), \
	MNEMONIC_DEF(I_VSHUFPS, "vshufps"), \
	MNEMONIC_DEF(I_VSHUFPD, "vshufpd"), \
	MNEMONIC_DEF(I_VPALIGNR, "vpalignr"), \
	MNEMONIC_DEF(I_VBLENDPS, "vblendps"), \
	MNEMONIC_DEF(I_VBLENDPD, "vblendpd"), \
	MNEMONIC_DEF(I_VPBLENDW, "vpblendw"), \
	MNEMONIC_DEF(I_VPBLENDD, "vpblendd"), \
	MNEMONIC_DEF(I_VPINSRB, "vpinsrb"), \
	MNEMONIC_DEF(I_VINSERTPS, "vinsertps"), \
	MNEMONIC_DEF(I_VPINSRD, "vpinsrd"), \
	MNEMONIC_DEF(I_VPINSRQ, "vpinsrq"), \
	MNEMONIC_DEF(I_VDPPS, "vdpps"), \
	MNEMONIC_DEF(I_VDPPD, "vdppd"), \
	MNEMONIC_DEF(I_VMPSADBW, "vmpsadbw"), \
	MNEMONIC_DEF(I_VPCLMULQDQ, "vpclmulqdq"), \
	MNEMONIC_DEF(I_VROUNDSS, "vroundss"), \
	MNEMONIC_DEF(I_VROUNDSD, "vroundsd"), \
	MNEMONIC_DEF(I_VPERM2F128, "vperm2f128"), \
	MNEMONIC_DEF(I_VINSERTF128, "vinsertf128"), \
	MNEMONIC_DEF(I_VPMACSSWW, "vpmacssww"), \
	MNEMONIC_DEF(I_VPMACSSWD, "vpmacsswd"), \
	MNEMONIC_DEF(I_VPMACSSDQL, "vpmacssdql"), \
	MNEMONIC_DEF(I_VPMACSSDQH, "vpmacssdqh"), \
	MNEMONIC_DEF(I_VPMACSWW, "vpmacsww"), \
	MNEMONIC_DEF(I_VPMACSWD, "vpmacswd"), \
	MNEMONIC_DEF(I_VPMACSDQL, "vpmacsdql"), \
	MNEMONIC_DEF(I_VPMADCSSWD, "vpmadcsswd"), \
	MNEMONIC_DEF(I_VPMADCSWD, "vpmadcswd"), \
	MNEMONIC_DEF(I_VPPERM, "vpperm"), \
	MNEMONIC_DEF(I_VPCMOV, "vpcmov"), \
	MNEMONIC_DEF(I_VPERMIL2PD, "vpermil2pd"), \
	MNEMONIC_DEF(I_VPERMIL2PS, "vpermil2ps"), \
	MNEMONIC_DEF(I_VPCOMB, "vpcomb"), \
	MNEMONIC_DEF(I_VPCOMW, "vpcomw"), \
	MNEMONIC_DEF(I_VPCOMD, "vpcomd"), \
	MNEMONIC_DEF(I_VPCOMQ, "vpcomq"), \
	MNEMONIC_DEF(I_VPCOMUB, "vpcomub"), \
	MNEMONIC_DEF(I_VPCOMUW, "vpcomuw"), \
	MNEMONIC_DEF(I_VPCOMUD, "vpcomud"), \
	MNEMONIC_DEF(I_VPCOMUQ, "vpcomuq"), \
	MNEMONIC_DEF(I_VPSRLDQ, "vpsrldq"), \
	MNEMONIC_DEF(I_VPSRLW, "vpsrlw"), \
	MNEMONIC_DEF(I_VPSRLD, "vpsrld"), \
	MNEMONIC_DEF(I_VPSRLQ, "vpsrlq"), \
	MNEMONIC_DEF(I_VPSRAW, "vpsraw"), \
	MNEMONIC_DEF(I_VPSRAD, "vpsrad"), \
	MNEMONIC_DEF(I_VPSLLW, "vpsllw"), \
	MNEMONIC_DEF(I_VPSLLD, "vpslld"), \
	MNEMONIC_DEF(I_VPSLLQ, "vpsllq"), \
	MNEMONIC_DEF(I_VFMADD132PD, "vfmadd132pd"), \
	MNEMONIC_DEF(I_VFMADD132PS, "vfmadd132ps"), \
	MNEMONIC_DEF(I_VFMADD213PD, "vfmadd213pd"), \
	MNEMONIC_DEF(I_VFMADD213PS, "vfmadd213ps"), \
	MNEMONIC_DEF(I_VFMADD231PD, "vfmadd231pd"), \
	MNEMONIC_DEF(I_VFMADD231PS, "vfmadd231ps"), \
	MNEMONIC_DEF(I_VFMADDSUB132PD, "vfmaddsub132pd"), \
	MNEMONIC_DEF(I_VFMADDSUB132PS, "vfmaddsub132ps"), \
	MNEMONIC_DEF(I_VFMADDSUB213PD, "vfmaddsub213pd"), \
	MNEMONIC_DEF(I_VFMADDSUB213PS, "vfmaddsub213ps"), \
	MNEMONIC_DEF(I_VFMADDSUB231PD, "vfmaddsub231pd"), \
	MNEMONIC_DEF(I_VFMADDSUB231PS, "vfmaddsub231ps"), \
	MNEMONIC_DEF(I_VFMSUBADD132PD, "vfmsubadd132pd"), \
	MNEMONIC_DEF(I_VFMSUBADD132PS, "vfmsubadd132ps"), \
	MNEMONIC_DEF(I_VFMSUBADD213PD, "vfmsubadd213pd"), \
	MNEMONIC_DEF(I_VFMSUBADD213PS, "vfmsubadd213ps"), \
	MNEMONIC_DEF(I_VFMSUBADD231PD, "vfmsubadd231pd"), \
	MNEMONIC_DEF(I_VFMSUBADD231PS, "vfmsubadd231ps"), \
	MNEMONIC_DEF(I_VFMSUB132PD, "vfmsub132pd"), \
	MNEMONIC_DEF(I_VFMSUB132PS, "vfmsub132ps"), \
	MNEMONIC_DEF(I_VFMSUB213PD, "vfmsub213pd"), \
	MNEMONIC_DEF(I_VFMSUB213PS, "vfmsub213ps"), \
	MNEMONIC_DEF(I_VFMSUB231PD, "vfmsub231pd"), \
	MNEMONIC_DEF(I_VFMSUB231PS, "vfmsub231ps"), \
	MNEMONIC_DEF(I_VFNMADD132PD, "vfnmadd132pd"), \
	MNEMONIC_DEF(I_VFNMADD132PS, "vfnmadd132ps"), \
	MNEMONIC_DEF(I_VFNMADD213PD, "vfnmadd213pd"), \
	MNEMONIC_DEF(I_VFNMADD213PS, "vfnmadd213ps"), \
	MNEMONIC_DEF(I_VFNMADD231PD, "vfnmadd231pd"), \
	MNEMONIC_DEF(I_VFNMADD231PS, "vfnmadd231ps"), \
	MNEMONIC_DEF(I_VFNMSUB132PD, "vfnmsub132pd"), \
	MNEMONIC_DEF(I_VFNMSUB132PS, "vfnmsub132ps"), \
	MNEMONIC_DEF(I_VFNMSUB213PD, "vfnmsub213pd"), \
	MNEMONIC_DEF(I_VFNMSUB213PS, "vfnmsub213ps"), \
	MNEMONIC_DEF(I_VFNMSUB231PD, "vfnmsub231pd"), \
	MNEMONIC_DEF(I_VFNMSUB231PS, "vfnmsub231ps"), \
	MNEMONIC_DEF(I_VFRCZPD, "vfrczpd"), \
	MNEMONIC_DEF(I_VFRCZPS, "vfrczps"), \
	MNEMONIC_DEF(I_VFRCZSD, "vfrczsd"), \
	MNEMONIC_DEF(I_VFRCZSS, "vfrczss"), \
	MNEMONIC_DEF(I_VPHADDBD, "vphaddbd"), \
	MNEMONIC_DEF(I_VPHADDBQ, "vphaddbq"), \
	MNEMONIC_DEF(I_VPHADDBW, "vphaddbw"), \
	MNEMONIC_DEF(I_VPHADDDQ, "vphadddq"), \
	MNEMONIC_DEF(I_VPHADDUBQ, "vphaddubq"), \
	MNEMONIC_DEF(I_VPHADDUBW, "vphaddubw"), \
	MNEMONIC_DEF(I_VPHADDUDQ, "vphaddudq"), \
	MNEMONIC_DEF(I_VPHADDUWD, "vphadduwd"), \
	MNEMONIC_DEF(I_VPHADDUWQ, "vphadduwq"), \
	MNEMONIC_DEF(I_VPHADDWD, "vphaddwd"), \
	MNEMONIC_DEF(I_VPHADDWQ, "vphaddwq"), \
	MNEMONIC_DEF(I_VPHSUBBW, "vphsubbw"), \
	MNEMONIC_DEF(I_VPHSUBDQ, "vphsubdq"), \
	MNEMONIC_DEF(I_VPHSUBWD, "vphsubwd"), \
	MNEMONIC_DEF(I_VPMACSDD, "vpmacsdd"), \
	MNEMONIC_DEF(I_VPMACSDQH, "vpmacsdqh"), \
	MNEMONIC_DEF(I_VPMACSSDD, "vpmacssdd"), \
	MNEMONIC_DEF(I_VPMACSSQH, "vpmacssqh"), \
	MNEMONIC_DEF(I_VPROTB, "vprotb"), \
	MNEMONIC_DEF(I_VPROTD, "vprotd"), \
	MNEMONIC_DEF(I_VPROTQ, "vprotq"), \
	MNEMONIC_DEF(I_VPROTW, "vprotw"), \
	MNEMONIC_DEF(I_VPSHAB, "vpshab"), \
	MNEMONIC_DEF(I_VPSHAD, "vpshad"), \
	MNEMONIC_DEF(I_VPSHAQ, "vpshaq"), \
	MNEMONIC_DEF(I_VPSHAW, "vpshaw"), \
	MNEMONIC_DEF(I_VPSHLB, "vpshlb"), \
	MNEMONIC_DEF(I_VPSHLD, "vpshld"), \
	MNEMONIC_DEF(I_VPSHLQ, "vpshlq"), \
	MNEMONIC_DEF(I_VPSHLW, "vpshlw"), \
	MNEMONIC_DEF(I_PFRCP, "pfrcp"), \
	MNEMONIC_DEF(I_PFRCPIT1, "pfrcpit1"), \
	MNEMONIC_DEF(I_PFMUL, "pfmul"), \
	MNEMONIC_DEF(I_PFRCPIT2, "pfrcpit2"), \
	MNEMONIC_DEF(I_PFCMPGE, "pfcmpge"), \
	MNEMONIC_DEF(I_PFRSQRT, "pfrsqrt"), \
	MNEMONIC_DEF(I_PFRSQIT1, "pfrsqit1"), \
	MNEMONIC_DEF(I_PFSUBR, "pfsubr"), \
	MNEMONIC_DEF(I_PSWAPD, "pswapd"), \
	MNEMONIC_DEF(I_PFPNACC, "pfpnacc"), \
	MNEMONIC_DEF(I_PFNACC, "pfnacc"), \
	MNEMONIC_DEF(I_PF2IW, "pf2iw"), \
	MNEMONIC_DEF(I_GETSEC, "getsec"), \
	MNEMONIC_DEF(I_XSTORE, "xstore"), \
	MNEMONIC_DEF(I_VPSHUFB, "vpshufb"), \
	MNEMONIC_DEF(I_VFMADD132SS, "vfmadd132ss"), \
	MNEMONIC_DEF(I_VFMADD132SD, "vfmadd132sd"), \
	MNEMONIC_DEF(I_VPHADDW, "vphaddw"), \
	MNEMONIC_DEF(I_VPHADDD, "vphaddd"), \
	MNEMONIC_DEF(I_VPHADDSW, "vphaddsw"), \
	MNEMONIC_DEF(I_VPMADDUBSW, "vpmaddubsw"), \
	MNEMONIC_DEF(I_VPHSUBW, "vphsubw"), \
	MNEMONIC_DEF(I_VPHSUBD, "vphsubd"), \
	MNEMONIC_DEF(I_VADDPD, "vaddpd"), \
	MNEMONIC_DEF(I_VADDPS, "vaddps"), \
	MNEMONIC_DEF(I_VPHSUBSW, "vphsubsw"), \
	MNEMONIC_DEF(I_VPSIGNB, "vpsignb"), \
	MNEMONIC_DEF(I_VPSIGNW, "vpsignw"), \
	MNEMONIC_DEF(I_VPSIGND, "vpsignd"), \
	MNEMONIC_DEF(I_VPMULHRSW, "vpmulhrsw"), \
	MNEMONIC_DEF(I_VPABSB, "vpabsb"), \
	MNEMONIC_DEF(I_VPABSW, "vpabsw"), \
	MNEMONIC_DEF(I_VPABSD, "vpabsd"), \
	MNEMONIC_DEF(I_VMOVLPS, "vmovlps"), \
	MNEMONIC_DEF(I_VMOVLPD, "vmovlpd"), \
	MNEMONIC_DEF(I_VUNPCKLPS, "vunpcklps"), \
	MNEMONIC_DEF(I_VUNPCKLPD, "vunpcklpd"), \
	MNEMONIC_DEF(I_VUNPCKHPS, "vunpckhps"), \
	MNEMONIC_DEF(I_VUNPCKHPD, "vunpckhpd"), \
	MNEMONIC_DEF(I_VMOVHPS, "vmovhps"), \
	MNEMONIC_DEF(I_VMOVLHPS, "vmovlhps"), \
	MNEMONIC_DEF(I_VMOVHPD, "vmovhpd"), \
	MNEMONIC_DEF(I_VANDPS, "vandps"), \
	MNEMONIC_DEF(I_VANDPD, "vandpd"), \
	MNEMONIC_DEF(I_VANDNPS, "vandnps"), \
	MNEMONIC_DEF(I_VANDNPD, "vandnpd"), \
	MNEMONIC_DEF(I_VORPS, "vorps"), \
	MNEMONIC_DEF(I_VORPD, "vorpd"), \
	MNEMONIC_DEF(I_VXORPS, "vxorps"), \
	MNEMONIC_DEF(I_VXORPD, "vxorpd"), \
	MNEMONIC_DEF(I_VMULPS, "vmulps"), \
	MNEMONIC_DEF(I_VMULPD, "vmulpd"), \
	MNEMONIC_DEF(I_VSUBPS, "vsubps"), \
	MNEMONIC_DEF(I_VSUBPD, "vsubpd"), \
	MNEMONIC_DEF(I_VMINPS, "vminps"), \
	MNEMONIC_DEF(I_VMINPD, "vminpd"), \
	MNEMONIC_DEF(I_VDIVPS, "vdivps"), \
	MNEMONIC_DEF(I_VDIVPD, "vdivpd"), \
	MNEMONIC_DEF(I_VMAXPS, "vmaxps"), \
	MNEMONIC_DEF(I_VMAXPD, "vmaxpd"), \
	MNEMONIC_DEF(I_VPUNPCKLBW, "vpunpcklbw"), \
	MNEMONIC_DEF(I_VPUNPCKLWD, "vpunpcklwd"), \
	MNEMONIC_DEF(I_VPUNPCKLDQ, "vpunpckldq"), \
	MNEMONIC_DEF(I_VPACKSSWB, "vpacksswb"), \
	MNEMONIC_DEF(I_VPCMPGTB, "vpcmpgtb"), \
	MNEMONIC_DEF(I_VPCMPGTW, "vpcmpgtw"), \
	MNEMONIC_DEF(I_VPCMPGTD, "vpcmpgtd"), \
	MNEMONIC_DEF(I_VPACKUSWB, "vpackuswb"), \
	MNEMONIC_DEF(I_VPUNPCKHBW, "vpunpckhbw"), \
	MNEMONIC_DEF(I_VPUNPCKHWD, "vpunpckhwd"), \
	MNEMONIC_DEF(I_VPUNPCKHDQ, "vpunpckhdq"), \
	MNEMONIC_DEF(I_VPACKSSDW, "vpackssdw"), \
	MNEMONIC_DEF(I_VPCMPEQB, "vpcmpeqb"), \
	MNEMONIC_DEF(I_VPCMPEQW, "vpcmpeqw"), \
	MNEMONIC_DEF(I_VPCMPEQD, "vpcmpeqd"), \
	MNEMONIC_DEF(I_VHADDPD, "vhaddpd"), \
	MNEMONIC_DEF(I_VHSUBPD, "vhsubpd"), \
	MNEMONIC_DEF(I_VPADDQ, "vpaddq"), \
	MNEMONIC_DEF(I_VPMULLW, "vpmullw"), \
	MNEMONIC_DEF(I_VPSUBUSB, "vpsubusb"), \
	MNEMONIC_DEF(I_VPSUBUSW, "vpsubusw"), \
	MNEMONIC_DEF(I_VPMINUB, "vpminub"), \
	MNEMONIC_DEF(I_VPAND, "vpand"), \
	MNEMONIC_DEF(I_VPADDUSB, "vpaddusb"), \
	MNEMONIC_DEF(I_VPADDUSW, "vpaddusw"), \
	MNEMONIC_DEF(I_VPMAXUB, "vpmaxub"), \
	MNEMONIC_DEF(I_VPANDN, "vpandn"), \
	MNEMONIC_DEF(I_VPAVGB, "vpavgb"), \
	MNEMONIC_DEF(I_VPAVGW, "vpavgw"), \
	MNEMONIC_DEF(I_VPMULHUW, "vpmulhuw"), \
	MNEMONIC_DEF(I_VPMULHW, "vpmulhw"), \
	MNEMONIC_DEF(I_VPSUBSB, "vpsubsb"), \
	MNEMONIC_DEF(I_VPSUBSW, "vpsubsw"), \
	MNEMONIC_DEF(I_VPMINSW, "vpminsw"), \
	MNEMONIC_DEF(I_VPOR, "vpor"), \
	MNEMONIC_DEF(I_VPADDSB, "vpaddsb"), \
	MNEMONIC_DEF(I_VPADDSW, "vpaddsw"), \
	MNEMONIC_DEF(I_VPMAXSW, "vpmaxsw"), \
	MNEMONIC_DEF(I_VPXOR, "vpxor"), \
	MNEMONIC_DEF(I_VPMULUDQ, "vpmuludq"), \
	MNEMONIC_DEF(I_VPMADDWD, "vpmaddwd"), \
	MNEMONIC_DEF(I_VPSADBW, "vpsadbw"), \
	MNEMONIC_DEF(I_VPSUBB, "vpsubb"), \
	MNEMONIC_DEF(I_VPSUBW, "vpsubw"), \
	MNEMONIC_DEF(I_VPSUBD, "vpsubd"), \
	MNEMONIC_DEF(I_VPSUBQ, "vpsubq"), \
	MNEMONIC_DEF(I_VPADDB, "vpaddb"), \
	MNEMONIC_DEF(I_VPADDW, "vpaddw"), \
	MNEMONIC_DEF(I_VPADDD, "vpaddd"), \
	MNEMONIC_DEF(I_VCVTSI2SS, "vcvtsi2ss"), \
	MNEMONIC_DEF(I_VSQRTSS, "vsqrtss"), \
	MNEMONIC_DEF(I_VRSQRTSS, "vrsqrtss"), \
	MNEMONIC_DEF(I_VRCPSS, "vrcpss"), \
	MNEMONIC_DEF(I_VMULSS, "vmulss"), \
	MNEMONIC_DEF(I_VSUBSS, "vsubss"), \
	MNEMONIC_DEF(I_VMINSS, "vminss"), \
	MNEMONIC_DEF(I_VDIVSS, "vdivss"), \
	MNEMONIC_DEF(I_VMAXSS, "vmaxss"), \
	MNEMONIC_DEF(I_VMULSD, "vmulsd"), \
	MNEMONIC_DEF(I_VSUBSD, "vsubsd"), \
	MNEMONIC_DEF(I_VMINSD, "vminsd"), \
	MNEMONIC_DEF(I_VDIVSD, "vdivsd"), \
	MNEMONIC_DEF(I_VMAXSD, "vmaxsd"), \
	MNEMONIC_DEF(I_VHADDPS, "vhaddps"), \
	MNEMONIC_DEF(I_VCVTSS2SD, "vcvtss2sd"), \
	MNEMONIC_DEF(I_VCVTSI2SD, "vcvtsi2sd"), \
	MNEMONIC_DEF(I_VSQRTSD, "vsqrtsd"), \
	MNEMONIC_DEF(I_VCVTSD2SS, "vcvtsd2ss"), \
	MNEMONIC_DEF(I_VHSUBPS, "vhsubps"), \
	MNEMONIC_DEF(I_VMOVUPS, "vmovups"), \
	MNEMONIC_DEF(I_VMOVAPS, "vmovaps"), \
	MNEMONIC_DEF(I_VCVTPS2PD, "vcvtps2pd"), \
	MNEMONIC_DEF(I_VRSQRTPS, "vrsqrtps"), \
	MNEMONIC_DEF(I_VMOVNTPS, "vmovntps"), \
	MNEMONIC_DEF(I_VUCOMISS, "vucomiss"), \
	MNEMONIC_DEF(I_VCOMISS, "vcomiss"), \
	MNEMONIC_DEF(I_VSQRTPS, "vsqrtps"), \
	MNEMONIC_DEF(I_VRCPPS, "VRCPPS"), \
	MNEMONIC_DEF(I_VCOMISD, "vcomisd"), \
	MNEMONIC_DEF(I_VUCOMISD, "vucomisd"), \
	MNEMONIC_DEF(I_VSQRTPD, "vsqrtpd"), \
	MNEMONIC_DEF(I_VMOVSLDUP, "vmovsldup"), \
	MNEMONIC_DEF(I_VMOVSHDUP, "vmovshdup"), \
	MNEMONIC_DEF(I_VMOVDDUP, "vmovddup"), \
	MNEMONIC_DEF(I_VCVTDQ2PS, "vcvtdq2ps"), \
	MNEMONIC_DEF(I_VLDMXCSR, "vldmxcsr"), \
	MNEMONIC_DEF(I_VSTMXCSR, "vstmxcsr"), \
	MNEMONIC_DEF(I_VMOVUPD, "vmovupd"), \
	MNEMONIC_DEF(I_VMOVAPD, "vmovapd"), \
	MNEMONIC_DEF(I_VMOVNTPD, "vmovntpd"), \
	MNEMONIC_DEF(I_VMOVD, "vmovd"), \
	MNEMONIC_DEF(I_VMOVQ, "vmovq"), \
	MNEMONIC_DEF(I_VMOVDQA, "vmovdqa"), \
	MNEMONIC_DEF(I_VMOVQQA, "vmovdqa"), \
	MNEMONIC_DEF(I_VCVTTSS2SI, "vcvttss2si"), \
	MNEMONIC_DEF(I_VCVTSS2SI, "vcvtss2si"), \
	MNEMONIC_DEF(I_VMOVDQU, "vmovdqu"), \
	MNEMONIC_DEF(I_VMOVQQU, "vmovdqu"), \
	MNEMONIC_DEF(I_VMOVHLPS, "vmovhlps"), \
	MNEMONIC_DEF(I_VCVTTPS2DQ, "vcvttps2dq"), \
	MNEMONIC_DEF(I_MOVNTSS, "movntss"), \
	MNEMONIC_DEF(I_PI2FD, "pi2fd"), \
	MNEMONIC_DEF(I_PF2ID, "pf2id"), \
	MNEMONIC_DEF(I_PFMAX, "pfmax"), \
	MNEMONIC_DEF(I_PAVGUSB, "pavgusb"), \
	MNEMONIC_DEF(I_PFADD, "pfadd"), \
	MNEMONIC_DEF(I_VMOVSD, "vmovsd"), \
	MNEMONIC_DEF(I_VCVTPS2DQ, "vcvtps2dq"), \
	MNEMONIC_DEF(I_VMOVNTDQ, "vmovntdq"), \
	MNEMONIC_DEF(I_VCVTTSD2SI, "vcvttsd2si"), \
	MNEMONIC_DEF(I_VCVTSD2SI, "vcvtsd2si"), \
	MNEMONIC_DEF(I_VMOVSS, "vmovss"), \
	MNEMONIC_DEF(I_MOVNTSD, "movntsd"), \
	MNEMONIC_DEF(I_INVVPID, "invvpid"), \
	MNEMONIC_DEF(I_MOVBE, "movbe"), \
	MNEMONIC_DEF(I_VPERMILPS, "vpermilps"), \
	MNEMONIC_DEF(I_VPERMILPD, "vpermilpd"), \
	MNEMONIC_DEF(I_VPMULDQ, "vpmuldq"), \
	MNEMONIC_DEF(I_VPACKUSDW, "vpackusdw"), \
	MNEMONIC_DEF(I_VMASKMOVPS, "vmaskmovps"), \
	MNEMONIC_DEF(I_VMASKMOVPD, "vmaskmovpd"), \
	MNEMONIC_DEF(I_VPMINSB, "vpminsb"), \
	MNEMONIC_DEF(I_VPMINSD, "vpminsd"), \
	MNEMONIC_DEF(I_VPMINUW, "vpminuw"), \
	MNEMONIC_DEF(I_VPMINUD, "vpminud"), \
	MNEMONIC_DEF(I_VPMAXSB, "vpmaxsb"), \
	MNEMONIC_DEF(I_VPMAXSD, "vpmaxsd"), \
	MNEMONIC_DEF(I_VPMAXUW, "vpmaxuw"), \
	MNEMONIC_DEF(I_VPMAXUD, "vpmaxud"), \
	MNEMONIC_DEF(I_VPMULLD, "vpmulld"), \
	MNEMONIC_DEF(I_VFMSUB132SS, "vfmsub132ss"), \
	MNEMONIC_DEF(I_VFNMSUB132SS, "vfnmsub132ss"), \
	MNEMONIC_DEF(I_VFNMADD132SS, "vfnmadd132ss"), \
	MNEMONIC_DEF(I_VFMADD213SS, "vfmadd213ss"), \
	MNEMONIC_DEF(I_VFMSUB213SS, "vfmsub213ss"), \
	MNEMONIC_DEF(I_VFNMADD213SS, "vfnmadd213ss"), \
	MNEMONIC_DEF(I_VFNMSUB213SS, "vfnmsub213ss"), \
	MNEMONIC_DEF(I_VFMADD231SS, "vfmadd231ss"), \
	MNEMONIC_DEF(I_VFMSUB231SS, "vfmsub231ss"), \
	MNEMONIC_DEF(I_VFNMADD231SS, "vfnmadd231ss"), \
	MNEMONIC_DEF(I_VFNMSUB231SS, "vfnmsub231ss"), \
	MNEMONIC_DEF(I_VAESENCLAST, "vaesenclast"), \
	MNEMONIC_DEF(I_VAESDEC, "vaesdec"), \
	MNEMONIC_DEF(I_VFMSUB132SD, "vfmsub132sd"), \
	MNEMONIC_DEF(I_VFNMADD132SD, "vfnmadd132sd"), \
	MNEMONIC_DEF(I_VFNMSUB132SD, "vfnmsub132sd"), \
	MNEMONIC_DEF(I_VFMADD213SD, "vfmadd213sd"), \
	MNEMONIC_DEF(I_VFMSUB213SD, "vfmsub213sd"), \
	MNEMONIC_DEF(I_VFNMADD213SD, "vfnmadd213sd"), \
	MNEMONIC_DEF(I_VFNMSUB213SD, "vfnmsub213sd"), \
	MNEMONIC_DEF(I_VFMADD231SD, "vfmadd231sd"), \
	MNEMONIC_DEF(I_VFMSUB231SD, "vfmsub231sd"), \
	MNEMONIC_DEF(I_VFNMADD231SD, "vfnmadd231sd"), \
	MNEMONIC_DEF(I_VFNMSUB231SD, "vfnmsub231sd"), \
	MNEMONIC_DEF(I_VAESDECLAST, "vaesdeclast"), \
	MNEMONIC_DEF(I_VTESTPS, "vtestps"), \
	MNEMONIC_DEF(I_VTESTPD, "vtestpd"), \
	MNEMONIC_DEF(I_VPTEST, "vptest"), \
	MNEMONIC_DEF(I_VBROADCASTSS, "vbroadcastss"), \
	MNEMONIC_DEF(I_VPBROADCASTD, "vpbroadcastd"), \
	MNEMONIC_DEF(I_VPBROADCASTQ, "vpbroadcastq"), \
	MNEMONIC_DEF(I_VBROADCASTI128, "vbroadcasti128"), \
	MNEMONIC_DEF(I_VPBROADCASTB, "vpbroadcastb"), \
	MNEMONIC_DEF(I_VPBROADCASTW, "vpbroadcastw"), \
	MNEMONIC_DEF(I_VPMOVSXBW, "vpmovsxbw"), \
	MNEMONIC_DEF(I_VPMOVSXBD, "vpmovsxbd"), \
	MNEMONIC_DEF(I_VPMOVSXBQ, "vpmovsxbq"), \
	MNEMONIC_DEF(I_VPMOVSXWD, "vpmovsxwd"), \
	MNEMONIC_DEF(I_VPMOVSXWQ, "vpmovsxwq"), \
	MNEMONIC_DEF(I_VPMOVSXDQ, "vpmovsxdq"), \
	MNEMONIC_DEF(I_VMOVNTDQA, "vmovntdqa"), \
	MNEMONIC_DEF(I_VPMOVZXBW, "vpmovzxbw"), \
	MNEMONIC_DEF(I_VPMOVZXBD, "vpmovzxbd"), \
	MNEMONIC_DEF(I_VPMOVZXBQ, "vpmovzxbq"), \
	MNEMONIC_DEF(I_VPMOVZXWD, "vpmovzxwd"), \
	MNEMONIC_DEF(I_VPMOVZXWQ, "vpmovzxwq"), \
	MNEMONIC_DEF(I_VPMOVZXDQ, "vpmovzxdq"), \
	MNEMONIC_DEF(I_VPHMINPOSUW, "vphminposuw"), \
	MNEMONIC_DEF(I_VBROADCASTSD, "vbroadcastsd"), \
	MNEMONIC_DEF(I_VBROADCASTF128, "vbroadcastf128"), \
	MNEMONIC_DEF(I_VBLENDVPS, "vblendvps"), \
	MNEMONIC_DEF(I_VBLENDVPD, "vblendvpd"), \
	MNEMONIC_DEF(I_VPBLENDVB, "vpblendvb"), \
	MNEMONIC_DEF(I_VPEXTRB, "vpextrb"), \
	MNEMONIC_DEF(I_VPUNPCKLQDQ, "vpunpcklqdq"), \
	MNEMONIC_DEF(I_VPUNPCKHQDQ, "vpunpckhqdq"), \
	MNEMONIC_DEF(I_VADDSS, "vaddss"), \
	MNEMONIC_DEF(I_VADDSD, "vaddsd"), \
	MNEMONIC_DEF(I_VADDSUBPS, "vaddsubps"), \
	MNEMONIC_DEF(I_VADDSUBPD, "vaddsubpd"), \
	MNEMONIC_DEF(I_VAESENC, "vaesenc"), \
	MNEMONIC_DEF(I_VAESIMC, "vaesimc"), \
	MNEMONIC_DEF(I_VCVTTPD2DQ, "vcvttpd2dq"), \
	MNEMONIC_DEF(I_VCVTDQ2PD, "vcvtdq2pd"), \
	MNEMONIC_DEF(I_VCVTPD2DQ, "vcvtpd2dq"), \
	MNEMONIC_DEF(I_VLDDQU, "vlddqu"), \
	MNEMONIC_DEF(I_VCVTPD2PS, "vcvtpd2ps"), \
	MNEMONIC_DEF(I_VPHADDUBD, "vphaddubd"), \
	MNEMONIC_DEF(I_FDISI, "fdisi"), \
	MNEMONIC_DEF(I_FENI, "feni"), \
	MNEMONIC_DEF(I_VZEROUPPER, "vzeroupper"), \
	MNEMONIC_DEF(I_VZEROALL, "vzeroall"), \
	MNEMONIC_DEF(I_VMOVMSKPS, "vmovmskps"), \
	MNEMONIC_DEF(I_VMOVMSKPD, "vmovmskpd"), \
	MNEMONIC_DEF(I_VPMOVMSKB, "vpmovmskb"), \
	MNEMONIC_DEF(I_VMASKMOVDQU, "vmaskmovdqu"), \
	MNEMONIC_DEF(I_XCRYPTECB, "xcryptecb"), \
	MNEMONIC_DEF(I_XCRYPTCBC, "xcryptcbc"), \
	MNEMONIC_DEF(I_XCRYPTCTR, "xcryptctr"), \
	MNEMONIC_DEF(I_XCRYPTCFB, "xcryptcfb"), \
	MNEMONIC_DEF(I_XCRYPTOFB, "xcryptofb"), \
	MNEMONIC_DEF(I_MONTMUL, "montmul"), \
	MNEMONIC_DEF(I_XSHA1, "xsha1"), \
	MNEMONIC_DEF(I_XSHA256, "xsha256"), \
	MNEMONIC_DEF(I_INSERTQ, "insertq"), \
	MNEMONIC_DEF(I_INVEPT, "invept"), \
	MNEMONIC_DEF(I_VPCMPEQQ, "vpcmpeqq"), \
	MNEMONIC_DEF(I_VCVTPS2PH, "vcvtps2ph"), \
	MNEMONIC_DEF(I_VCVTPH2PS, "vcvtph2ps"), \
	MNEMONIC_DEF(I_RDRAND, "rdrand"), \
	MNEMONIC_DEF(I_RDSEED, "rdseed"), \
	MNEMONIC_DEF(I_VPSHUFD, "vpshufd"), \
	MNEMONIC_DEF(I_VPSHUFHW, "vpshufhw"), \
	MNEMONIC_DEF(I_VPSHUFLW, "vpshuflw"), \
	MNEMONIC_DEF(I_VEXTRACTF128, "vextractf128"), \
	MNEMONIC_DEF(I_VEXTRACTPS, "vextractps"), \
	MNEMONIC_DEF(I_VPCMPESTRI, "vpcmpestri"), \
	MNEMONIC_DEF(I_VPCMPESTRM, "vpcmpestrm"), \
	MNEMONIC_DEF(I_VPCMPISTRI, "vpcmpistri"), \
	MNEMONIC_DEF(I_VPCMPISTRM, "vpcmpistrm"), \
	MNEMONIC_DEF(I_VPCMPGTQ, "vpcmpgtq"), \
	MNEMONIC_DEF(I_VPEXTRW, "vpextrw"), \
	MNEMONIC_DEF(I_VPEXTRD, "vpextrd"), \
	MNEMONIC_DEF(I_VPEXTRQ, "vpextrq"), \
	MNEMONIC_DEF(I_VROUNDPD, "vroundpd"), \
	MNEMONIC_DEF(I_VROUNDPS, "vroundps"), \
	MNEMONIC_DEF(I_VPERMD, "vpermd"), \
	MNEMONIC_DEF(I_VPERMPD, "vpermpd"), \
	MNEMONIC_DEF(I_VPERMPS, "vpermps"), \
	MNEMONIC_DEF(I_VPERMQ, "vpermq"), \
	MNEMONIC_DEF(I_VPERM2I128, "vperm2i128"), \
	MNEMONIC_DEF(I_VEXTRACTI128, "vextracti128"), \
	MNEMONIC_DEF(I_VINSERTI128, "vinserti128"), \
	MNEMONIC_DEF(I_VPMASKMOVD, "vpmaskmovd"), \
	MNEMONIC_DEF(I_VPMASKMOVQ, "vpmaskmovq"), \
	MNEMONIC_DEF(I_VPSLLVD, "vpsllvd"), \
	MNEMONIC_DEF(I_VPSLLVQ, "vpsllvq"), \
	MNEMONIC_DEF(I_VPSRAVD, "vpsravd"), \
	MNEMONIC_DEF(I_VPSRLVD, "vpsrlvd"), \
	MNEMONIC_DEF(I_VPSRLVQ, "vpsrlvq"), \
	MNEMONIC_DEF(I_SHA1RNDS4, "sha1rnds4"), \
	MNEMONIC_DEF(I_SHA1NEXTE, "sha1nexte"), \
	MNEMONIC_DEF(I_SHA1MSG1, "sha1msg1"), \
	MNEMONIC_DEF(I_SHA1MSG2, "sha1msg2"), \
	MNEMONIC_DEF(I_SHA256RNDS2, "sha256rnds2"), \
	MNEMONIC_DEF(I_SHA256MSG1, "sha256msg1"), \
	MNEMONIC_DEF(I_SHA256MSG2, "sha256msg2"), \
	MNEMONIC_DEF(I_RORX, "rorx"), \
	MNEMONIC_DEF(I_ANDN, "andn"), \
	MNEMONIC_DEF(I_PEXT, "pext"), \
	MNEMONIC_DEF(I_MULX, "mulx"), \
	MNEMONIC_DEF(I_SARX, "sarx"), \
	MNEMONIC_DEF(I_SHLX, "shlx"), \
	MNEMONIC_DEF(I_SHRX, "shrx"), \

#define MNEMONIC_DEF(id, name) id
enum class MnemonicType { MNEMONIC_MAP_DEF };

#undef MNEMONIC_DEF
#define MNEMONIC_DEF(id, name) name

static const char MNEMONICS[][16] = { MNEMONIC_MAP_DEF };

}

#endif // _X86BOX_MNEMONIC_H_